version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

volumes:
  data:
